### ISSUE TITLE
同學，你洩漏了很多人的個資喔

### ISSUE THREAD

**Issue by dada8397** [katrina376/cccloud#1]
https://github.com/katrina376/cccloud/blob/9498a3ce26f753545f6c9f9cf18d857917c7b981/importSQL/comp01.sql
像這樣的 sql 檔最好不要推到 github 上 XD
建議一下而已

**Comment by katrina376** [comment]
你好，
感謝指正！

這是我好多年前還是小菜鳥時期寫的東西了，根本完全忘了它的存在 囧"
我晚點會把這個 repo 刪掉。
